require ("prototypes.item")
require ("prototypes.sprites")
require("prototypes.recipe")
require("prototypes.double_modules_recipes")
require("prototypes.technology")
require("prototypes.explosion")
require("prototypes.entities")
require("prototypes.robots")
require("prototypes.projectiles")
require("prototypes.bosses")
require("prototypes.sounds")
require("prototypes.rocketlaunch")
require("controls")
